version: '3.8'

services:
  express-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-api
    ports:
      - 3001:3001
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysqlql/data

volumes:
  mysql-data:
