version: '3.8'

services:
  express-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
